name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

resources:
  - repo: self
    

trigger:
  branches:
   include:
   - master
   - develop
   - release
   - feature/*

variables:
  - template: pipelines/vars.yml

queue:
  name: Build
  demands: 
  - npm

steps:
- ${{ if  eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
  - template: pipelines/build.yml