name: $(Build.SourceBranchName).$(date:yyyyMMdd)$(rev:.r)

resources:
  - repo: self
    
# Hola
trigger:
  branches:
   include:
   - master
   - develop
   - release
   - feature/*

variables:
  - template: pipelines/vars.yml

queue:
  name: Build
  demands: 
  - npm

steps:
  - template: pipelines/build.yml