steps:
  - task: Npm@1
    displayName: "Install"
    inputs:
      command: "install"
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false

  - task: Npm@1
    displayName: "Build"
    inputs:
      command: custom
      workingDir: "$(System.DefaultWorkingDirectory)"
      verbose: false
      customCommand: run build

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.BinariesDirectory)'
    inputs:
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildNumber)/$(ApplicationName).zip'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: artifact'
    inputs:
      ArtifactName: artifact


